### ISSUE TITLE
Router method changes

### ISSUE THREAD

**Issue by jberger** [RogerDodger/Mojolicious-Plugin-PlainRoutes#2]
Hello, I've noticed that you use at least one of the routing methods removed in Mojolicious 9.0, these include route, via, detour, and over. The fixes are all easy to do and are listed on the Upgrading wiki https://github.com/mojolicious/mojo/wiki/Upgrading

Thanks

**Comment by RogerDodger** [comment]
Fixed in 097534b983d4c673f674e7ad0eb83b746fe33f6b. Thanks for the heads up!
